language: node_js
node_js:
  - 6
  - 4
  - 0.12
  - 0.10

sudo: false

addons:
  postgresql: 9.3
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - mongodb
  - redis-server

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi

before_script:
  - psql -U postgres -c 'create database travis_ci_test;'
  - psql -U postgres -c 'create extension postgis;' travis_ci_test
