language: node_js
node_js:
  - 0.12
  - 0.10

sudo: false

services:
  - mongodb
  - redis-server

before_script:
  - psql -U postgres -c 'create extension postgis; create database travis;'

addons:
  postgresql: 9.3
